package sap_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	Document      struct {
		DocumentNo     string `json:"document_no"`
		DeliverTo      string `json:"deliver_to"`
		Quantity       string `json:"quantity"`
		PickedQuantity string `json:"picked_quantity"`
		Price          string `json:"price"`
		Batch          string `json:"batch"`
	} `json:"document"`
	ProductionOrder struct {
		DocumentNo           string `json:"document_no"`
		Status               string `json:"status"`
		DeliverTo            string `json:"deliver_to"`
		Quantity             string `json:"quantity"`
		CompletedQuantity    string `json:"completed_quantity"`
		PlannedStartDate     string `json:"planned_start_date"`
		PlannedValidatedDate string `json:"planned_validated_date"`
		ActualStartDate      string `json:"actual_start_date"`
		ActualValidatedDate  string `json:"actual_validated_date"`
		Batch                string `json:"batch"`
		Work                 struct {
			WorkNo                   string `json:"work_no"`
			Quantity                 string `json:"quantity"`
			CompletedQuantity        string `json:"completed_quantity"`
			ErroredQuantity          string `json:"errored_quantity"`
			Component                string `json:"component"`
			PlannedComponentQuantity string `json:"planned_component_quantity"`
			PlannedStartDate         string `json:"planned_start_date"`
			PlannedStartTime         string `json:"planned_start_time"`
			PlannedValidatedDate     string `json:"planned_validated_date"`
			PlannedValidatedTime     string `json:"planned_validated_time"`
			ActualStartDate          string `json:"actual_start_date"`
			ActualStartTime          string `json:"actual_start_time"`
			ActualValidatedDate      string `json:"actual_validated_date"`
			ActualValidatedTime      string `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"production_order"`
	APISchema     string `json:"api_schema"`
	MaterialCode  string `json:"material_code"`
	Plant         string `json:"plant/supplier"`
	Stock         string `json:"stock"`
	DocumentType  string `json:"document_type"`
	DocumentNo    string `json:"document_no"`
	PlannedDate   string `json:"planned_date"`
	ValidatedDate string `json:"validated_date"`
	Deleted       bool   `json:"deleted"`
}

type SDC struct {
	ConnectionKey          string `json:"connection_key"`
	Result                 bool   `json:"result"`
	RedisKey               string `json:"redis_key"`
	Filepath               string `json:"filepath"`
	ChatActivityCollection struct {
		ObjectID                                             string `json:"ObjectID"`
		ETag                                                 string `json:"ETag"`
		TypeCode                                             string `json:"TypeCode"`
		TypeCodeText                                         string `json:"TypeCodeText"`
		LifeCycleStatusCode                                  string `json:"LifeCycleStatusCode"`
		LifeCycleStatusCodeText                              string `json:"LifeCycleStatusCodeText"`
		LastChangeDate                                       string `json:"LastChangeDate"`
		ActivityWorklistItemUUID                             string `json:"ActivityWorklistItemUUID"`
		ActualDuration                                       string `json:"ActualDuration"`
		ActualEndDateTime                                    string `json:"ActualEndDateTime"`
		ActualStartDateTime                                  string `json:"ActualStartDateTime"`
		ActivitySentimentTypeCode                            string `json:"ActivitySentimentTypeCode"`
		ActivitySentimentTypeCodeText                        string `json:"ActivitySentimentTypeCodeText"`
		AdditionalLocationName                               string `json:"AdditionalLocationName"`
		AvailabilityCode                                     string `json:"AvailabilityCode"`
		AvailabilityCodeText                                 string `json:"AvailabilityCodeText"`
		BouncedIndicator                                     string `json:"BouncedIndicator"`
		CompletionDateTime                                   string `json:"CompletionDateTime"`
		CompletionPercent                                    string `json:"CompletionPercent"`
		CorrespondenceTransmissionStatusCode                 string `json:"CorrespondenceTransmissionStatusCode"`
		CorrespondenceTransmissionStatusCodeText             string `json:"CorrespondenceTransmissionStatusCodeText"`
		CreationDate                                         string `json:"CreationDate"`
		DataOriginTypeCode                                   string `json:"DataOriginTypeCode"`
		DataOriginTypeCodeText                               string `json:"DataOriginTypeCodeText"`
		DistributionChannelCode                              string `json:"DistributionChannelCode"`
		DistributionChannelCodeText                          string `json:"DistributionChannelCodeText"`
		DistributionChannelDeterminationMethodCode           string `json:"DistributionChannelDeterminationMethodCode"`
		DistributionChannelDeterminationMethodCodeText       string `json:"DistributionChannelDeterminationMethodCodeText"`
		DivisionCode                                         string `json:"DivisionCode"`
		DivisionCodeText                                     string `json:"DivisionCodeText"`
		DivisionDeterminationMethodCode                      string `json:"DivisionDeterminationMethodCode"`
		DivisionDeterminationMethodCodeText                  string `json:"DivisionDeterminationMethodCodeText"`
		ExternalName                                         string `json:"ExternalName"`
		FullDayIndicator                                     string `json:"FullDayIndicator"`
		GroupwareItemID                                      string `json:"GroupwareItemID"`
		GroupCode                                            string `json:"GroupCode"`
		GroupCodeText                                        string `json:"GroupCodeText"`
		GroupwareSynchronizationNonRelevanceIndicator        string `json:"GroupwareSynchronizationNonRelevanceIndicator"`
		ID                                                   string `json:"ID"`
		InformationSensitivityCode                           string `json:"InformationSensitivityCode"`
		InformationSensitivityCodeText                       string `json:"InformationSensitivityCodeText"`
		InitiatingActivityUUID                               string `json:"InitiatingActivityUUID"`
		InitiatorCode                                        string `json:"InitiatorCode"`
		InitiatorCodeText                                    string `json:"InitiatorCodeText"`
		LocationName                                         string `json:"LocationName"`
		MarkedForDeletionDate                                string `json:"MarkedForDeletionDate"`
		MarkedForDeletion                                    string `json:"MarkedForDeletion"`
		MigratedDataAdaptationTypeCode                       string `json:"MigratedDataAdaptationTypeCode"`
		MigratedDataAdaptationTypeCodeText                   string `json:"MigratedDataAdaptationTypeCodeText"`
		PerfectStoreIndicator                                string `json:"PerfectStoreIndicator"`
		PlannedDuration                                      string `json:"PlannedDuration"`
		PredecessorActivityUUID                              string `json:"PredecessorActivityUUID"`
		PriorityCode                                         string `json:"PriorityCode"`
		PriorityCodeText                                     string `json:"PriorityCodeText"`
		ProcessingTypeCode                                   string `json:"ProcessingTypeCode"`
		ProcessingTypeCodeText                               string `json:"ProcessingTypeCodeText"`
		ReportedDate                                         string `json:"ReportedDate"`
		ReportedDateTime                                     string `json:"ReportedDateTime"`
		SalesOrganisationID                                  string `json:"SalesOrganisationID"`
		SalesOrganisationUUID                                string `json:"SalesOrganisationUUID"`
		SalesOrganizationDeterminationMethodCode             string `json:"SalesOrganizationDeterminationMethodCode"`
		SalesOrganizationDeterminationMethodCodeText         string `json:"SalesOrganizationDeterminationMethodCodeText"`
		SalesTerritoryDeterminationMethodCode                string `json:"SalesTerritoryDeterminationMethodCode"`
		SalesTerritoryDeterminationMethodCodeText            string `json:"SalesTerritoryDeterminationMethodCodeText"`
		SalesTerritoryID                                     string `json:"SalesTerritoryID"`
		SalesTerritoryUUID                                   string `json:"SalesTerritoryUUID"`
		ScheduledEndDate                                     string `json:"ScheduledEndDate"`
		ScheduledStartDate                                   string `json:"ScheduledStartDate"`
		SilentDataMigrationID                                string `json:"SilentDataMigrationID"`
		SocialMediaActivityProviderUUID                      string `json:"SocialMediaActivityProviderUUID"`
		ActivityFollowUpServiceRequestBlockingReasonCode     string `json:"ActivityFollowUpServiceRequestBlockingReasonCode"`
		ActivityFollowUpServiceRequestBlockingReasonCodeText string `json:"ActivityFollowUpServiceRequestBlockingReasonCodeText"`
		StatusSchemaName                                     string `json:"StatusSchemaName"`
		SubjectName                                          string `json:"SubjectName"`
		TransmittedDate                                      string `json:"TransmittedDate"`
		VisitWorkItemGenerationCode                          string `json:"VisitWorkItemGenerationCode"`
		VisitWorkItemGenerationCodeText                      string `json:"VisitWorkItemGenerationCodeText"`
		VisitTypeCode                                        string `json:"VisitTypeCode"`
		VisitTypeCodeText                                    string `json:"VisitTypeCodeText"`
		VisitTourPlanUUID                                    string `json:"VisitTourPlanUUID"`
		ChatMainPartyUUID                                    string `json:"ChatMainPartyUUID"`
		ChatMainPartyID                                      string `json:"ChatMainPartyID"`
		ChatMainEmailURI                                     string `json:"ChatMainEmailURI"`
		EntityLastChangedOn                                  string `json:"EntityLastChangedOn"`
		ChatActivityParties                                  struct {
			ObjectID                   string `json:"ObjectID"`
			ParentObjectID             string `json:"ParentObjectID"`
			ETag                       string `json:"ETag"`
			ChatActivityID             string `json:"ChatActivityID"`
			PartyUUID                  string `json:"PartyUUID"`
			PartyID                    string `json:"PartyID"`
			PartyTypeCode              string `json:"PartyTypeCode"`
			PartyTypeCodeText          string `json:"PartyTypeCodeText"`
			RoleCode                   string `json:"RoleCode"`
			RoleCodeText               string `json:"RoleCodeText"`
			RoleCategoryCode           string `json:"RoleCategoryCode"`
			RoleCategoryCodeText       string `json:"RoleCategoryCodeText"`
			PartyEmailURI              string `json:"PartyEmailURI"`
			MainIndicator              bool   `json:"MainIndicator"`
			PartyName                  string `json:"PartyName"`
			ToParentObjectID           string `json:"ToParent_ObjectID"`
			ChatActivityTextCollection struct {
				ObjectID            string `json:"ObjectID"`
				ParentObjectID      string `json:"ParentObjectID"`
				ETag                string `json:"ETag"`
				Text                string `json:"Text"`
				LanguageCode        string `json:"LanguageCode"`
				LanguageCodeText    string `json:"LanguageCodeText"`
				TypeCode            string `json:"TypeCode"`
				TypeCodeText        string `json:"TypeCodeText"`
				AuthorUUID          string `json:"AuthorUUID"`
				AuthorName          string `json:"AuthorName"`
				CreatedOn           string `json:"CreatedOn"`
				CreatedBy           string `json:"CreatedBy"`
				UpdatedOn           string `json:"UpdatedOn"`
				LastUpdatedBy       string `json:"LastUpdatedBy"`
				EntityLastChangedOn string `json:"EntityLastChangedOn"`
			} `json:"ChatActivityTextCollection"`
		} `json:"ChatActivityParties"`
	} `json:"ChatActivityCollection"`
	APISchema        string   `json:"api_schema"`
	Accepter         []string `json:"accepter"`
	ChatActivityCode string   `json:"chat_activity_code"`
	Deleted          bool     `json:"deleted"`
}
